added the previous PR changes to new branch
Layr-Labs/eigenlayer-contracts pull request #292
Opened 2023-10-26 13:18 UTC by Gajesh2007

2023-10-26 16:43 UTC, Sidu28 requested changes
This seems fine but it looks like you've left out some of the changes present in the previous PR: https://github.com/Layr-Labs/eigenlayer-contracts/pull/274/files

2023-10-26 18:45 UTC, Gajesh2007 commented
which one are u referring to?

2023-10-26 19:08 UTC, Sidu28 commented
> which one are u referring to?

you made edits to testDeployEigenPodTooSoon and testWithdrawBeforeRestaking in the previous PR, those changes aren't showing here as far as I can tell

2023-10-27 15:12 UTC, Sidu28 commented on src/test/EigenPod.t.sol
> +    function testStakingWithInvalidAmount () public {
can you move this test to EigenPodUnit.t.sol and then do the test with pod.stake instead of podManager.stake

2023-10-27 15:19 UTC, Sidu28 requested changes
look at my comment above ^^ otherwise lgtm

2023-10-27 15:28 UTC, Sidu28 approved these changes

2023-10-27 15:31 UTC, Sidu28 requested changes
CI failing @Gajesh2007

2023-10-27 16:45 UTC, merged