made forceUndelegate queue a withdrawal for each strategy
Layr-Labs/eigenlayer-contracts pull request #345
Opened 2023-11-22 12:25 UTC by Gajesh2007

2023-11-27 23:56 UTC, ChaoticWalrus commented on src/contracts/core/DelegationManager.sol
> -        // if no delegatable shares, return zero root, and don't queue a withdrawal
I'm not sure why some of these in-line comments are being deleted -- I find them helpful for clarity / splitting up the execution into "logical blocks", personally

2023-11-28 00:00 UTC, ChaoticWalrus requested changes
This PR looks really good!
The change has pluses and minuses, but I do like how it gives stakes more flexibility in how they complete these withdrawals.
I'm surprised this PR doesn't require more changes to tests -- this does flag to me a potential area with low(ish) test coverage.

Requesting one main change here: this PR should be targeting the `m2-mainnet` branch instead of the `master` branch. I have a question about in-line comments too (bit of a small nit, but I think I'd like to see them restored if you lack a reason for deleting them).

2023-11-28 21:19 UTC, ChaoticWalrus commented
> quick question - should i branch out `m2-mainnet`? and open new PR?

I think it would have been good to do this, but I'm pretty sure (like 95%+?) that you can just change the "target" branch of the PR and it should all be just fine, and you avoid having to duplicate work.

2023-11-30 11:12 UTC, Gajesh2007 commented
done.

2023-11-30 11:13 UTC, Gajesh2007 commented
oh wait. there are a ton of changes. do we need this?

2023-12-15 18:06 UTC, ChaoticWalrus commented
> oh wait. there are a ton of changes. should we merge the other changes?

fuuuuuu guess I was wrong, we should have duplicated the PR, I'm sorry!

2023-12-15 18:07 UTC, ChaoticWalrus commented
Changed the base branch back to make this PR readable

2023-12-15 20:23 UTC, wadealexc commented on src/contracts/core/DelegationManager.sol
> +            for (uint i = 0; i < strategies.length; i++) {
`uint256`

2023-12-15 22:14 UTC, ChaoticWalrus commented
Looking into getting this into shape rn

2023-12-17 22:49 UTC, wadealexc approved these changes

2023-12-18 02:34 UTC, merged