fix: compile warnings
Layr-Labs/eigenlayer-contracts pull request #664
Opened 2024-08-07 16:39 UTC by 0xClandestine

2024-09-20 13:49 UTC, wadealexc commented
![image](https://github.com/user-attachments/assets/bc8794c2-f472-4ed8-9963-16e19803103e)

Still getting some compiler warnings -- must be new since the rebase!

Looks good otherwise, thanks for the cleanup.

2024-09-20 13:49 UTC, wadealexc requested changes
See above ^ should be good once these are fixed

2024-10-03 15:24 UTC, ypatil12 approved these changes

2024-10-03 15:42 UTC, wadealexc approved these changes

2024-10-03 15:44 UTC, merged