feat: add selector upload to workflows
Layr-Labs/eigenlayer-contracts pull request #728
Opened 2024-09-05 14:51 UTC by stevennevins

**Motivation:**

Custom errors need to be uploaded to places like openchain.xyz so they're parsable by block explorers / viem / and other tooling

**Modifications:**

Adds workflow to upload selectors to a shared database

**Result:**

custom error selectors will be publicly searchable on openchain.xyz

2024-11-20 17:47 UTC, ypatil12 approved these changes
LGTM

2025-02-20 20:03 UTC, bowenli86 commented
@stevennevins what does this pr do? can you add details in PR description?

2025-03-02 23:01 UTC, stevennevins commented
> @stevennevins what's the motivation? how does this pr achieve it? can you add details in PR description?

updated

2025-03-03 15:26 UTC, 0xClandestine requested changes

2025-03-03 15:26 UTC, 0xClandestine commented on .github/workflows/upload-selectors.yml
> +name: 📤 Publish Selectors
Name should be formatted similarly to other workflows, tryna keep them organized.

2025-03-03 15:30 UTC, stevennevins commented on .github/workflows/upload-selectors.yml
> +  push:
We won’t do it if it’s manual

the command takes a handful of seconds if the contracts are compiled and is smart enough to only upload selectors that the database doesn’t already know about

2025-03-03 15:31 UTC, stevennevins commented on .github/workflows/upload-selectors.yml
> +  push:
Right now I do it manually when the sdk guys hit a new unknown revert selector

2025-03-03 15:31 UTC, stevennevins commented on .github/workflows/upload-selectors.yml
> +          forge selectors upload --all
wdym

2025-03-03 19:00 UTC, bowenli86 commented
does this need to run for every commit in dev and other branches? or only upon a release? 

iiuc, it's the latter? cc @0xClandestine @ypatil12

2025-03-04 21:24 UTC, stevennevins commented
> does this need to run for every commit in dev and other branches? or only upon a release?
> 
> iiuc, it's the latter? cc @0xClandestine @ypatil12

should just run on dev, mainnet, testnet branches. if it's just on release or for every commit on those branches I'm okay with either if anyone has strong opinions

2025-05-01 21:30 UTC, closed without merging