DRAFT: DM Cleanup
Layr-Labs/eigenlayer-contracts pull request #788
Opened 2024-10-02 09:08 UTC by ypatil12

This PR updates the storage of the delegationManager to store the operator's magnitude as part of its shares. Thus, we essentially store $$b_n$$ in this [doc](https://www.notion.so/eigen-labs/Slashing-Accounting-70dde029a6bb40628bcd56d351bf7e54#4caca6e758ab47e9a5edf26a19679596)

In doing so, we only need two types of shares

1. DepositShares: shares that are deposited in strategyManager/EPM
2. Shares: Exists in DM. For a staker, this is withdrawable shares. For an operator, this is the sum of its stakers withdrawable shares. This lives in storage for an operator but not for a staker. 

What I'm looking for feedback on:

- How do we feel about removing custom types and going for `depositShares` and `shares` everywhere
- Naming of depositShares/shares
- How do we feel about updating `operatorShares` on slash? 

Note: this only compiles for SM/DM, not EPM.

TODOs:

- [ ] Fix EPM compilation
- [ ] Clean up naming upon feedback
- [ ] Clean up refs to SlashingLib functions (add params when calling)

2024-10-02 19:03 UTC, gpsanant commented on src/contracts/core/DelegationManagerStorage.sol
> +    mapping(address => mapping(IStrategy => StakerScalingFactors)) public stakerDepositScalingFactor;
why

2024-10-02 19:06 UTC, gpsanant commented on src/contracts/core/StrategyManager.sol
> +    function removeDepositShares(address staker, IStrategy strategy, uint256 sharesToRemove) external onlyDelegationManager {
this is gross, because the parameter name should be `depositSharesToRemove`

2024-10-02 19:06 UTC, gpsanant commented on src/contracts/core/StrategyManagerStorage.sol
> +    mapping(address => mapping(IStrategy => uint256)) public stakerDepositShares;
is it ok to break this interface?

2024-10-02 19:07 UTC, gpsanant commented on src/contracts/interfaces/IShareManager.sol
> +    function removeDepositShares(address staker, IStrategy strategy, uint256 depositShares) external;
i feel like we have to make changes to EigenPodManager to comply w this?

2024-10-02 19:10 UTC, gpsanant commented on src/contracts/libraries/SlashingLib.sol
> +        uint64 operatorMagnitude
just magnitude

2024-10-02 19:10 UTC, gpsanant commented on src/contracts/libraries/SlashingLib.sol
> +        uint256 currentPlusAddedDepositShares = currentShares + addedDepositShares;
`newShares`

2024-10-02 19:34 UTC, gpsanant commented on src/contracts/core/DelegationManager.sol
> +                uint256[] memory singleOwnedShare = new uint256[](1);
`singleDepositShares`

2024-10-02 19:43 UTC, gpsanant commented on src/contracts/libraries/SlashingLib.sol
> +    function getOperatorSharesAfterSlash(uint256 operatorShares, uint64 newOperatorMagnitude) internal pure returns (uint256) {
this needs the old magnitude and the new magnitude

2024-10-02 19:49 UTC, gpsanant commented on src/contracts/core/DelegationManager.sol
> +     * TODO: make cleaner, get rid of assembly
assembly is broken

2024-10-02 19:50 UTC, gpsanant commented on src/contracts/core/DelegationManager.sol
> +    function getDepositedShares(
why are we changing the semantic meaning here. this should be shares, not depositShares

2024-10-02 19:58 UTC, gpsanant commented on src/contracts/core/DelegationManager.sol
> -        Shares existingShares,
just move this into increaseDelegation at this point

2024-10-02 19:59 UTC, gpsanant commented on src/contracts/core/DelegationManager.sol
> +    function getDepositedShares(
ah i see what you did. this is fine

2024-10-02 20:00 UTC, gpsanant requested changes
few comments and todos

2024-10-04 16:28 UTC, wadealexc commented on src/contracts/core/AllocationManager.sol
> +            delegation.decreaseOperatorShares(operator, strategies[i], totalMagnitudeBeforeSlashing, uint64(totalMagnitudes.latest()));
Can we calc and reuse rather than reading from state?

`uint64 totalMagnitudeAfterSlashing = totalMagnitudeBeforeSlashing - slashedMagnitude`

2024-10-04 22:14 UTC, gpsanant commented
Will get naming feedback later

2024-10-04 22:14 UTC, merged